=== cds-snc/platform-forms-client/lib/middleware/schemas/templates.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "id": "https://forms-formulaires.alpha.canada.ca/",
  "type": "object",
  "title": "GC Forms Schema - Alpha",
  "description": "A schema to define a Forms configuration.",
  "default": {},
  "examples": [
    {
      "titleEn": "",
      "titleFr": "",
      "introduction": {},
      "privacyPolicy": {},
      "confirmation": {},
      "layout": [],
      "elements": [],
      "startPage": {},
      "brand": {}
    }
  ],
  "properties": {
    "titleEn": {
      "description": "The displayed title of the form to the user in English",
      "id": "#/properties/titleEn",
      "type": "string"
    },
    "titleFr": {
      "description": "The displayed title of the form to the user in French",
      "id": "#/properties/titleFr",
      "type": "string"
    },
    "introduction": {
      "description": "Form introduction",
      "id": "#/properties/introduction",
      "type": "object",
      "properties": {
        "descriptionEn": {
          "type": "string"
        },
        "descriptionFr": {
          "type": "string"
        }
      }
    },
    "privacyPolicy": {
      "description": "Form privacy policy",
      "id": "#/properties/privacyPolicy",
      "type": "object",
      "properties": {
        "descriptionEn": {
          "type": "string"
        },
        "descriptionFr": {
          "type": "string"
        }
      }
    },
    "confirmation": {
      "description": "Content that will be displayed after a form is submitted.",
      "id": "#/properties/confirmation",
      "type": "object",
      "properties": {
        "descriptionEn": {
          "type": "string"
        },
        "descriptionFr": {
          "type": "string"
        },
        "referrerUrlEn": {
          "type": "string"
        },
        "referrerUrlFr": {
          "type": "string"
        }
      }
    },
    "layout": {
      "description": "A list of element IDs that determines the order or elements in the form.",
      "type": "array",
      "items": {
        "type": "number"
      },
      "uniqueItems": true,
      "examples": [[2, 3, 4, 6, 9, 5]]
    },
    "groups": {
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the group.",
          "type": "string"
        },
        "titleEn": {
          "description": "The title of the group in English.",
          "type": "string"
        },
        "titleFr": {
          "description": "The title of the group in French.",
          "type": "string"
        },
        "nextAction": {
          "description": "The next action to take i.e. next group or submit.",
          "type": "string"
        },
        "elements": {
          "description": "A list of elements contained within the form group.",
          "type": "array"
        }
      }
    },
    "groupsLayout": {
      "description": "A list of group IDs that determines the order of the groups in the form.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "examples": [["one", "two"]]
    },
    "elements": {
      "description": "A list of elements contained within the form.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/element"
      },
      "examples": [
        {
          "id": 1,
          "type": "richText",
          "properties": {
            "validation": {
              "required": false
            },
            "descriptionEn": "#### Section 1: Nomination Category",
            "descriptionFr": "#### Section 1: Catégorie de la nomination"
          }
        },
        {
          "id": 2,
          "uuid": "12345678-1234-1234-1234-123456789012",
          "type": "radio",
          "properties": {
            "questionId": "my_custom_id",
            "tags": ["radio", "nomination"],
            "choices": [
              {
                "en": "Team nomination",
                "fr": "Mise en candidature d’une équipe"
              },
              {
                "en": "Individual Nomination",
                "fr": "Mise en candidature d’une personne"
              }
            ],
            "titleEn": "Is this a Team or Individual Nomination?",
            "titleFr": "Is this a Team or Individual Nomination?",
            "validation": {
              "required": true
            },
            "descriptionEn": "",
            "descriptionFr": ""
          }
        }
      ]
    },
    "brand": {
      "type": "object",
      "properties": {
        "name": {
          "description": "The brand name.",
          "type": "string"
        },
        "urlEn": {
          "description": "URL for English version of the site.",
          "type": "string"
        },
        "urlFr": {
          "description": "URL for a French version of the site.",
          "type": "string"
        },
        "logoEn": {
          "description": "English logo path.",
          "type": "string"
        },
        "logoFr": {
          "description": "French logo path.",
          "type": "string"
        },
        "logoTitleEn": {
          "description": "logo title.",
          "type": "string"
        },
        "logoTitleFr": {
          "description": "logo title.",
          "type": "string"
        },
        "disableGCBranding": {
          "description": "If set to true, GC branding will not be rendered in the footer.",
          "type": "boolean"
        }
      }
    },
    "lastGeneratedElementId": {
      "description": "The last generated element id",
      "type": "number"
    }
  },
  "required": ["titleEn", "titleFr", "privacyPolicy", "confirmation", "layout", "elements"],
  "additionalProperties": false,
  "definitions": {
    "element": {
      "type": "object",
      "properties": {
        "id": {
          "description": "The unique id for the object",
          "type": "integer",
          "minimum": 1
        },
        "uuid": {
          "description": "A unique id for the object (future use)",
          "type": "string",
          "format": "uuid"
        },
        "type": {
          "type": "string",
          "enum": [
            "textField",
            "textArea",
            "dropdown",
            "radio",
            "checkbox",
            "fileInput",
            "dynamicRow",
            "richText",
            "attestation",
            "combobox",
            "addressComplete",
            "formattedDate"
          ]
        },
        "properties": {
          "type": "object",
          "properties": {
            "questionId": {
              "description": "A user-defined unique id for the question",
              "type": "string"
            },
            "tags": {
              "description": "A list of tags that can be used to group elements together.",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "titleEn": {
              "description": "Input label in English",
              "type": "string"
            },
            "titleFr": {
              "description": "Input label in French",
              "type": "string"
            },
            "placeholderEn": {
              "description": "Text that will appear in the text input field as a placeholder in English",
              "type": "string"
            },
            "placeholderFr": {
              "description": "Text that will appear in the text input field as a placeholder in French",
              "type": "string"
            },
            "descriptionEn": {
              "description": "Secondary paragraph/text of a question or element that provides additional context beyond the label in English",
              "type": "string"
            },
            "descriptionFr": {
              "description": "Secondary paragraph/text of a question or element that provides additional context beyond the label in French",
              "type": "string"
            },
            "dynamicRow": {
              "type": "object",
              "properties": {
                "rowTitleEn": {
                  "type": "string",
                  "description": "The title of the row in English"
                },
                "rowTitleFr": {
                  "type": "string",
                  "description": "The title of the row in French"
                },
                "addButtonTextEn": {
                  "type": "string",
                  "description": "Text for the add button in English"
                },
                "removeButtonTextEn": {
                  "type": "string",
                  "description": "Text for the remove button in English"
                },
                "addButtonTextFr": {
                  "type": "string",
                  "description": "Text for the add button in French"
                },
                "removeButtonTextFr": {
                  "type": "string",
                  "description": "Text for the remove button in French"
                }
              }
            },
            "choices": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "en": {
                    "description": "English choice",
                    "type": "string"
                  },
                  "fr": {
                    "description": "French choice",
                    "type": "string"
                  }
                }
              }
            },
            "sortOrder": {
              "type": "string",
              "description": "Controls how choices are displayed",
              "enum": ["none", "ascending", "descending"],
              "default": "none"
            },
            "managedChoices": {
              "type": ["array", "string"],
              "description": "The name of the data file(s) containing the choices for this element."
            },
            "conditionalRules": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "choiceId": {
                    "description": "The id of the element that will trigger the conditional rule",
                    "type": "string",
                    "minimum": 1
                  }
                }
              }
            },
            "maxNumberOfRows": {
              "type": "integer",
              "minimum": 1
            },
            "strictValue": {
              "description": "If set to true, the element will only accept values that are in the choices list.",
              "type": "boolean"
            },
            "validation": {
              "type": "object",
              "properties": {
                "required": {
                  "type": "boolean"
                },
                "type": {
                  "type": "string",
                  "enum": ["email", "alphanumeric", "text", "name", "number", "phone", "date"]
                },
                "regex": {
                  "type": "string"
                },
                "maxLength": {
                  "description": "The maximum number of characters that can be entered in a textinput or textarea.",
                  "type": "integer",
                  "minimum": 1
                },
                "descriptionEn": {
                  "type": "string"
                },
                "descriptionFr": {
                  "type": "string"
                },
                "all": {
                  "description": "Used only for checkboxes, ignored on other elements. When set to true, this will require that all checkboxes be selected. Used typically for the attestation section.",
                  "type": "boolean"
                }
              },
              "examples": [
                {
                  "validation": {
                    "required": true,
                    "type": "email",
                    "descriptionEn": "Enter a valid email address.",
                    "descriptionFr": "Veuillez entrer une adresse courriel valide."
                  }
                },
                {
                  "validation": {
                    "required": false,
                    "type": "alphanumeric",
                    "descriptionEn": "Please enter your home street address.",
                    "descriptionFr": "Veuillez entrer votre adresse postale."
                  }
                }
              ]
            },
            "subElements": {
              "description": "A list of subElements contained within a dynamicRow",
              "type": "array",
              "items": {
                "$ref": "#/definitions/element"
              }
            }
          }
        }
      },
      "required": ["id", "type", "properties"]
    }
  }
}

=== cds-snc/platform-forms-client/__fixtures__/publishTestForm.json
{
  "titleEn": "A Publishable Form",
  "titleFr": "A Publishable Form (FR)",
  "introduction": {
    "descriptionEn": "",
    "descriptionFr": ""
  },
  "privacyPolicy": {
    "descriptionEn": "A Privacy Statement",
    "descriptionFr": "A Privacy Statement (FR)"
  },
  "confirmation": {
    "descriptionEn": "Confirmed",
    "descriptionFr": "Confirmed (FR)",
    "referrerUrlEn": "",
    "referrerUrlFr": ""
  },
  "layout": [1],
  "elements": [
    {
      "id": 1,
      "type": "textField",
      "properties": {
        "questionId": "",
        "tags": [],
        "subElements": [],
        "choices": [
          {
            "en": "",
            "fr": ""
          }
        ],
        "titleEn": "Just one question",
        "titleFr": "Just one question (FR)",
        "validation": {
          "required": false
        },
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      },
      "uuid": "afff49e6-1cdb-482d-82f8-9ef8ad6879ef"
    }
  ],
  "groups": {
    "start": {
      "name": "Start",
      "titleEn": "Start page",
      "titleFr": "Start page",
      "elements": ["1"],
      "nextAction": "review"
    },
    "review": {
      "name": "Review",
      "titleEn": "End (Review page and Confirmation)",
      "titleFr": "End (Review page and Confirmation)",
      "elements": [],
      "nextAction": "end"
    },
    "end": {
      "name": "End",
      "titleEn": "Confirmation page",
      "titleFr": "Confirmation page",
      "elements": []
    }
  },
  "groupsLayout": [],
  "lastGeneratedElementId": 1
}

=== cds-snc/platform-forms-client/__fixtures__/requiredAttributesTestForm.json
{
  "titleEn": "A Required Attributes Test Form",
  "titleFr": "",
  "introduction": {
    "descriptionEn": "",
    "descriptionFr": ""
  },
  "privacyPolicy": {
    "descriptionEn": "",
    "descriptionFr": ""
  },
  "confirmation": {
    "descriptionEn": "",
    "descriptionFr": "",
    "referrerUrlEn": "",
    "referrerUrlFr": ""
  },
  "layout": [1, 2, 3, 4],
  "elements": [
    {
      "id": 1,
      "type": "textField",
      "properties": {
        "questionId": "",
        "tags": [],
        "subElements": [],
        "choices": [
          {
            "en": "",
            "fr": ""
          }
        ],
        "titleEn": "A Required Short Answer",
        "titleFr": "",
        "validation": {
          "required": true
        },
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      },
      "uuid": "e853dee1-b66e-4fba-a5f0-e8a68b96089c"
    },
    {
      "id": 2,
      "type": "checkbox",
      "properties": {
        "questionId": "",
        "tags": [],
        "subElements": [],
        "choices": [
          {
            "en": "One",
            "fr": ""
          },
          {
            "en": "Two",
            "fr": ""
          },
          {
            "en": "Three",
            "fr": ""
          }
        ],
        "titleEn": "A Required Multiple Choice",
        "titleFr": "",
        "validation": {
          "required": true
        },
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      },
      "uuid": "9485a4ea-6fd8-4575-a018-47c65f71c271"
    },
    {
      "id": 3,
      "type": "radio",
      "properties": {
        "questionId": "",
        "tags": [],
        "subElements": [],
        "choices": [
          {
            "en": "One",
            "fr": ""
          },
          {
            "en": "Two",
            "fr": ""
          },
          {
            "en": "Three",
            "fr": ""
          }
        ],
        "titleEn": "A Required Radio",
        "titleFr": "",
        "validation": {
          "required": true
        },
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      },
      "uuid": "67474906-7b0b-4f08-b209-45902da0f193"
    },
    {
      "id": 4,
      "type": "dropdown",
      "properties": {
        "questionId": "",
        "tags": [],
        "subElements": [],
        "choices": [
          {
            "en": "One",
            "fr": ""
          },
          {
            "en": "Two",
            "fr": ""
          },
          {
            "en": "Three",
            "fr": ""
          }
        ],
        "titleEn": "A Required Dropdown",
        "titleFr": "",
        "validation": {
          "required": true
        },
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      },
      "uuid": "1ec7e4fb-8d18-4eca-9870-83fb3356de7e"
    }
  ],
  "groups": {
    "start": {
      "name": "Start",
      "titleEn": "Start page",
      "titleFr": "Start page",
      "elements": ["1", "2", "3", "4"],
      "nextAction": "review"
    },
    "review": {
      "name": "Review",
      "titleEn": "End (Review page and Confirmation)",
      "titleFr": "End (Review page and Confirmation)",
      "elements": [],
      "nextAction": "end"
    },
    "end": {
      "name": "End",
      "titleEn": "Confirmation page",
      "titleFr": "Confirmation page",
      "elements": []
    }
  },
  "groupsLayout": [],
  "lastGeneratedElementId": 4
}

=== cds-snc/platform-forms-client/__fixtures__/navigationFocus.json
{
  "titleEn": "Navigation Focus",
  "titleFr": "[FR]Navigation Focus",
  "introduction": {
    "descriptionEn": "",
    "descriptionFr": ""
  },
  "privacyPolicy": {
    "descriptionEn": "Privacy statement",
    "descriptionFr": "[FR]p"
  },
  "confirmation": {
    "descriptionEn": "c",
    "descriptionFr": "c",
    "referrerUrlEn": "",
    "referrerUrlFr": ""
  },
  "layout": [4, 1, 2, 3],
  "elements": [
    {
      "id": 4,
      "type": "textField",
      "properties": {
        "choices": [
          {
            "en": "",
            "fr": ""
          }
        ],
        "titleEn": "Full name",
        "titleFr": "Nom complet",
        "validation": {
          "required": false
        },
        "subElements": [],
        "autoComplete": "name",
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      }
    },
    {
      "id": 3,
      "type": "textField",
      "uuid": "97d37bc1-a464-4514-9818-6dd1a416c6f2",
      "properties": {
        "choices": [
          {
            "en": "",
            "fr": ""
          }
        ],
        "titleEn": "QB",
        "titleFr": "[FR]QB",
        "validation": {
          "required": true
        },
        "subElements": [],
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      }
    },
    {
      "id": 2,
      "type": "textField",
      "uuid": "ec3ad6f9-29a2-48da-83e7-d93b43eae478",
      "properties": {
        "choices": [
          {
            "en": "",
            "fr": ""
          }
        ],
        "titleEn": "QA",
        "titleFr": "[FR]QA",
        "validation": {
          "required": true
        },
        "subElements": [],
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      }
    },
    {
      "id": 1,
      "type": "radio",
      "uuid": "f86151dd-d246-4f44-9156-6058ab63229d",
      "properties": {
        "choices": [
          {
            "en": "A",
            "fr": "[FR]A"
          },
          {
            "en": "B",
            "fr": "[FR]B"
          }
        ],
        "titleEn": "Page?",
        "titleFr": "[FR]Page?",
        "validation": {
          "required": true
        },
        "subElements": [],
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      }
    }
  ],
  "groups": {
    "start": {
      "name": "Start",
      "titleEn": "Start page",
      "titleFr": "Start page",
      "autoFlow": false,
      "elements": ["4", "1"],
      "nextAction": [
        {
          "groupId": "bd4c615d-fef5-4a38-b1f0-c73954803867",
          "choiceId": "1.0"
        },
        {
          "groupId": "60756820-065f-42fd-9d8d-198770a46c7b",
          "choiceId": "1.1"
        }
      ]
    },
    "bd4c615d-fef5-4a38-b1f0-c73954803867": {
      "name": "A",
      "titleEn": "A",
      "titleFr": "[FR]A",
      "autoFlow": false,
      "elements": ["2"],
      "nextAction": "review"
    },
    "60756820-065f-42fd-9d8d-198770a46c7b": {
      "name": "B",
      "titleEn": "B",
      "titleFr": "[FR]B",
      "autoFlow": true,
      "elements": ["3"],
      "nextAction": "review"
    },
    "review": {
      "name": "Review",
      "titleEn": "End (Review page and Confirmation)",
      "titleFr": "End (Review page and Confirmation)",
      "elements": [],
      "nextAction": "end"
    },
    "end": {
      "name": "End",
      "titleEn": "Confirmation page",
      "titleFr": "Confirmation page",
      "elements": []
    }
  },
  "groupsLayout": ["bd4c615d-fef5-4a38-b1f0-c73954803867", "60756820-065f-42fd-9d8d-198770a46c7b"],
  "lastGeneratedElementId": 4
}

=== cds-snc/platform-forms-client/__fixtures__/textFieldTestForm.json
{
  "titleEn": "Text Field Test Form",
  "titleFr": "TExt Field Test Form (FR)",
  "confirmation": {
    "descriptionEn": "# Submitted thank you!",
    "descriptionFr": "# Submitted thank you (FR)",
    "referrerUrlEn": "https://digital.canada.ca/",
    "referrerUrlFr": "https://numerique.canada.ca/"
  },
  "privacyPolicy": {
    "descriptionEn": "Privacy statement",
    "descriptionFr": "[FR] Privacy statement"
  },
  "layout": [1, 2],
  "elements": [
    {
      "id": 1,
      "type": "richText",
      "properties": {
        "descriptionEn": "## Test Section with Text Fields",
        "descriptionFr": "## Test Section with Text Fields (FR)",
        "validation": {
          "required": false
        }
      }
    },
    {
      "id": 2,
      "type": "textField",
      "properties": {
        "titleEn": "Text Field 1",
        "titleFr": "Text Field 1 (FR)",
        "placeholderEn": "text field 1 placeholder",
        "placeholderFr": "text field 1 placeholder (FR)",
        "descriptionEn": "text field 1 description",
        "descriptionFr": "text field 1 description (FR)",
        "validation": {
          "required": true,
          "maxLength": 40
        }
      }
    }
  ]
}

=== cds-snc/platform-forms-client/__fixtures__/attestationTestForm.json
{
  "titleEn": "An Attestation Test Form",
  "titleFr": "An Attestation Test Form [FR]",
  "introduction": {
    "descriptionEn": "",
    "descriptionFr": ""
  },
  "privacyPolicy": {
    "descriptionEn": "A privacy statement",
    "descriptionFr": "A privacy statement [FR]"
  },
  "confirmation": {
    "descriptionEn": "A confirmation message",
    "descriptionFr": "A confirmation message",
    "referrerUrlEn": "",
    "referrerUrlFr": ""
  },
  "layout": [2, 1],
  "elements": [
    {
      "id": 2,
      "type": "textField",
      "properties": {
        "choices": [
          {
            "en": "",
            "fr": ""
          }
        ],
        "titleEn": "Full name",
        "titleFr": "Nom complet",
        "validation": {
          "required": false
        },
        "subElements": [],
        "autoComplete": "name",
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      }
    },
    {
      "id": 1,
      "type": "checkbox",
      "uuid": "e70e3168-6ca8-4f2a-bd5e-049f33896f34",
      "properties": {
        "choices": [
          {
            "en": "Condition 1",
            "fr": "Condition 1"
          },
          {
            "en": "Condition 2",
            "fr": "Condition 2"
          },
          {
            "en": "Condition 3",
            "fr": "Condition 3"
          }
        ],
        "titleEn": "I agree to:",
        "titleFr": "J'accepte :",
        "validation": {
          "all": true,
          "required": true
        },
        "subElements": [],
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      }
    }
  ],
  "groups": {
    "end": {
      "name": "End",
      "titleEn": "Confirmation page",
      "titleFr": "Confirmation page",
      "elements": []
    },
    "start": {
      "name": "Start",
      "titleEn": "Start page",
      "titleFr": "Start page",
      "elements": ["2", "1"],
      "nextAction": "review"
    },
    "review": {
      "name": "Review",
      "titleEn": "End (Review page and Confirmation)",
      "titleFr": "End (Review page and Confirmation)",
      "elements": [],
      "nextAction": "end"
    }
  },
  "groupsLayout": [],
  "lastGeneratedElementId": 2
}
