=== cds-snc/platform-forms-client/lib/middleware/schemas/templates.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "id": "https://forms-formulaires.alpha.canada.ca/",
  "type": "object",
  "title": "GC Forms Schema - Alpha",
  "description": "A schema to define a Forms configuration.",
  "default": {},
  "examples": [
    {
      "titleEn": "",
      "titleFr": "",
      "introduction": {},
      "privacyPolicy": {},
      "confirmation": {},
      "layout": [],
      "elements": [],
      "startPage": {},
      "brand": {}
    }
  ],
  "properties": {
    "titleEn": {
      "description": "The displayed title of the form to the user in English",
      "id": "#/properties/titleEn",
      "type": "string"
    },
    "titleFr": {
      "description": "The displayed title of the form to the user in French",
      "id": "#/properties/titleFr",
      "type": "string"
    },
    "introduction": {
      "description": "Form introduction",
      "id": "#/properties/introduction",
      "type": "object",
      "properties": {
        "descriptionEn": {
          "type": "string"
        },
        "descriptionFr": {
          "type": "string"
        }
      }
    },
    "privacyPolicy": {
      "description": "Form privacy policy",
      "id": "#/properties/privacyPolicy",
      "type": "object",
      "properties": {
        "descriptionEn": {
          "type": "string"
        },
        "descriptionFr": {
          "type": "string"
        }
      }
    },
    "confirmation": {
      "description": "Content that will be displayed after a form is submitted.",
      "id": "#/properties/confirmation",
      "type": "object",
      "properties": {
        "descriptionEn": {
          "type": "string"
        },
        "descriptionFr": {
          "type": "string"
        },
        "referrerUrlEn": {
          "type": "string"
        },
        "referrerUrlFr": {
          "type": "string"
        }
      }
    },
    "layout": {
      "description": "A list of element IDs that determines the order or elements in the form.",
      "type": "array",
      "items": {
        "type": "number"
      },
      "uniqueItems": true,
      "examples": [[2, 3, 4, 6, 9, 5]]
    },
    "groups": {
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the group.",
          "type": "string"
        },
        "titleEn": {
          "description": "The title of the group in English.",
          "type": "string"
        },
        "titleFr": {
          "description": "The title of the group in French.",
          "type": "string"
        },
        "nextAction": {
          "description": "The next action to take i.e. next group or submit.",
          "type": "string"
        },
        "elements": {
          "description": "A list of elements contained within the form group.",
          "type": "array"
        }
      }
    },
    "groupsLayout": {
      "description": "A list of group IDs that determines the order of the groups in the form.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "examples": [["one", "two"]]
    },
    "elements": {
      "description": "A list of elements contained within the form.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/element"
      },
      "examples": [
        {
          "id": 1,
          "type": "richText",
          "properties": {
            "validation": {
              "required": false
            },
            "descriptionEn": "#### Section 1: Nomination Category",
            "descriptionFr": "#### Section 1: Catégorie de la nomination"
          }
        },
        {
          "id": 2,
          "uuid": "12345678-1234-1234-1234-123456789012",
          "type": "radio",
          "properties": {
            "questionId": "my_custom_id",
            "tags": ["radio", "nomination"],
            "choices": [
              {
                "en": "Team nomination",
                "fr": "Mise en candidature d’une équipe"
              },
              {
                "en": "Individual Nomination",
                "fr": "Mise en candidature d’une personne"
              }
            ],
            "titleEn": "Is this a Team or Individual Nomination?",
            "titleFr": "Is this a Team or Individual Nomination?",
            "validation": {
              "required": true
            },
            "descriptionEn": "",
            "descriptionFr": ""
          }
        }
      ]
    },
    "brand": {
      "type": "object",
      "properties": {
        "name": {
          "description": "The brand name.",
          "type": "string"
        },
        "urlEn": {
          "description": "URL for English version of the site.",
          "type": "string"
        },
        "urlFr": {
          "description": "URL for a French version of the site.",
          "type": "string"
        },
        "logoEn": {
          "description": "English logo path.",
          "type": "string"
        },
        "logoFr": {
          "description": "French logo path.",
          "type": "string"
        },
        "logoTitleEn": {
          "description": "logo title.",
          "type": "string"
        },
        "logoTitleFr": {
          "description": "logo title.",
          "type": "string"
        },
        "disableGCBranding": {
          "description": "If set to true, GC branding will not be rendered in the footer.",
          "type": "boolean"
        }
      }
    },
    "lastGeneratedElementId": {
      "description": "The last generated element id",
      "type": "number"
    }
  },
  "required": ["titleEn", "titleFr", "privacyPolicy", "confirmation", "layout", "elements"],
  "additionalProperties": false,
  "definitions": {
    "element": {
      "type": "object",
      "properties": {
        "id": {
          "description": "The unique id for the object",
          "type": "integer",
          "minimum": 1
        },
        "uuid": {
          "description": "A unique id for the object (future use)",
          "type": "string",
          "format": "uuid"
        },
        "type": {
          "type": "string",
          "enum": [
            "textField",
            "textArea",
            "dropdown",
            "radio",
            "checkbox",
            "fileInput",
            "dynamicRow",
            "richText",
            "attestation",
            "combobox",
            "addressComplete",
            "formattedDate"
          ]
        },
        "properties": {
          "type": "object",
          "properties": {
            "questionId": {
              "description": "A user-defined unique id for the question",
              "type": "string"
            },
            "tags": {
              "description": "A list of tags that can be used to group elements together.",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "titleEn": {
              "description": "Input label in English",
              "type": "string"
            },
            "titleFr": {
              "description": "Input label in French",
              "type": "string"
            },
            "placeholderEn": {
              "description": "Text that will appear in the text input field as a placeholder in English",
              "type": "string"
            },
            "placeholderFr": {
              "description": "Text that will appear in the text input field as a placeholder in French",
              "type": "string"
            },
            "descriptionEn": {
              "description": "Secondary paragraph/text of a question or element that provides additional context beyond the label in English",
              "type": "string"
            },
            "descriptionFr": {
              "description": "Secondary paragraph/text of a question or element that provides additional context beyond the label in French",
              "type": "string"
            },
            "dynamicRow": {
              "type": "object",
              "properties": {
                "rowTitleEn": {
                  "type": "string",
                  "description": "The title of the row in English"
                },
                "rowTitleFr": {
                  "type": "string",
                  "description": "The title of the row in French"
                },
                "addButtonTextEn": {
                  "type": "string",
                  "description": "Text for the add button in English"
                },
                "removeButtonTextEn": {
                  "type": "string",
                  "description": "Text for the remove button in English"
                },
                "addButtonTextFr": {
                  "type": "string",
                  "description": "Text for the add button in French"
                },
                "removeButtonTextFr": {
                  "type": "string",
                  "description": "Text for the remove button in French"
                }
              }
            },
            "choices": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "en": {
                    "description": "English choice",
                    "type": "string"
                  },
                  "fr": {
                    "description": "French choice",
                    "type": "string"
                  }
                }
              }
            },
            "sortOrder": {
              "type": "string",
              "description": "Controls how choices are displayed",
              "enum": ["none", "ascending", "descending"],
              "default": "none"
            },
            "managedChoices": {
              "type": ["array", "string"],
              "description": "The name of the data file(s) containing the choices for this element."
            },
            "conditionalRules": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "choiceId": {
                    "description": "The id of the element that will trigger the conditional rule",
                    "type": "string",
                    "minimum": 1
                  }
                }
              }
            },
            "maxNumberOfRows": {
              "type": "integer",
              "minimum": 1
            },
            "strictValue": {
              "description": "If set to true, the element will only accept values that are in the choices list.",
              "type": "boolean"
            },
            "validation": {
              "type": "object",
              "properties": {
                "required": {
                  "type": "boolean"
                },
                "type": {
                  "type": "string",
                  "enum": ["email", "alphanumeric", "text", "name", "number", "phone", "date"]
                },
                "regex": {
                  "type": "string"
                },
                "maxLength": {
                  "description": "The maximum number of characters that can be entered in a textinput or textarea.",
                  "type": "integer",
                  "minimum": 1
                },
                "descriptionEn": {
                  "type": "string"
                },
                "descriptionFr": {
                  "type": "string"
                },
                "all": {
                  "description": "Used only for checkboxes, ignored on other elements. When set to true, this will require that all checkboxes be selected. Used typically for the attestation section.",
                  "type": "boolean"
                }
              },
              "examples": [
                {
                  "validation": {
                    "required": true,
                    "type": "email",
                    "descriptionEn": "Enter a valid email address.",
                    "descriptionFr": "Veuillez entrer une adresse courriel valide."
                  }
                },
                {
                  "validation": {
                    "required": false,
                    "type": "alphanumeric",
                    "descriptionEn": "Please enter your home street address.",
                    "descriptionFr": "Veuillez entrer votre adresse postale."
                  }
                }
              ]
            },
            "subElements": {
              "description": "A list of subElements contained within a dynamicRow",
              "type": "array",
              "items": {
                "$ref": "#/definitions/element"
              }
            }
          }
        }
      },
      "required": ["id", "type", "properties"]
    }
  }
}

=== cds-snc/platform-forms-client/__fixtures__/showHideTest.json
{
  "titleEn": "Show hide test",
  "titleFr": "",
  "introduction": {
    "descriptionEn": "",
    "descriptionFr": ""
  },
  "privacyPolicy": {
    "descriptionEn": "",
    "descriptionFr": ""
  },
  "confirmation": {
    "descriptionEn": "",
    "descriptionFr": "",
    "referrerUrlEn": "",
    "referrerUrlFr": ""
  },
  "layout": [1, 2],
  "elements": [
    {
      "id": 1,
      "type": "radio",
      "uuid": "48bacadf-a046-4c66-bcaa-cd8671d0a50c",
      "properties": {
        "tags": [],
        "choices": [
          {
            "en": "a",
            "fr": "a"
          },
          {
            "en": "b",
            "fr": "b"
          }
        ],
        "titleEn": "My radio element",
        "titleFr": "My radio elemen",
        "questionId": "",
        "validation": {
          "required": false
        },
        "subElements": [],
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      }
    },
    {
      "id": 2,
      "type": "textArea",
      "uuid": "99968cd7-9275-4ffe-b509-168e3cb1326d",
      "properties": {
        "tags": [],
        "choices": [],
        "titleEn": "More",
        "titleFr": "More",
        "questionId": "",
        "validation": {
          "required": false
        },
        "subElements": [],
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": "",
        "conditionalRules": [
          {
            "choiceId": "1.1"
          }
        ]
      }
    }
  ],
  "groups": {
    "end": {
      "name": "End",
      "titleEn": "Confirmation page",
      "titleFr": "Page de confirmation",
      "elements": []
    },
    "start": {
      "name": "Start",
      "titleEn": "Start page",
      "titleFr": "Page de départ",
      "elements": ["1", "2"],
      "nextAction": "review"
    },
    "review": {
      "name": "Review",
      "titleEn": "End (Review page and Confirmation)",
      "titleFr": "Fin (Page récapitulative et confirmation)",
      "elements": [],
      "nextAction": "end"
    }
  },
  "groupsLayout": [],
  "lastGeneratedElementId": 2
}

=== cds-snc/platform-forms-client/app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses-pilot/lib/__tests__/fixtures/template-get-support-cmeaj61dl0001xf01aja6mnpf.json
{
  "titleEn": "Get support",
  "titleFr": "Get support",
  "introduction": { "descriptionEn": "", "descriptionFr": "" },
  "privacyPolicy": { "descriptionEn": "Privacy statement", "descriptionFr": "Privacy statement" },
  "confirmation": {
    "descriptionEn": "Thanks - we'll get back to you.",
    "descriptionFr": "Thanks - we'll get back to you.",
    "referrerUrlEn": "",
    "referrerUrlFr": ""
  },
  "layout": [2, 8, 9, 10, 11, 12, 13, 14],
  "elements": [
    {
      "id": 14,
      "type": "textArea",
      "uuid": "4a9a23b5-3a89-4e87-b8f7-1910138e1c79",
      "properties": {
        "tags": [],
        "choices": [{ "en": "", "fr": "" }],
        "titleEn": "Tell us more ",
        "titleFr": "Tell us more ",
        "questionId": "",
        "validation": { "required": true },
        "subElements": [],
        "descriptionEn": "Please do not include any protected or personal information.",
        "descriptionFr": "Please do not include any protected or personal information.",
        "placeholderEn": "",
        "placeholderFr": ""
      }
    },
    {
      "id": 12,
      "type": "radio",
      "uuid": "4c3cbe6e-90f0-4328-b160-5dafb74c795c",
      "properties": {
        "tags": [],
        "choices": [
          { "en": "Ask a question", "fr": "Ask a question" },
          { "en": "Get help using GC Forms", "fr": "Get help using GC Forms" },
          {
            "en": "Request technical support with the API",
            "fr": "Request technical support with the API"
          },
          {
            "en": "Report a problem with a published form",
            "fr": "Report a problem with a published form"
          },
          { "en": "Other ", "fr": "Autre " }
        ],
        "titleEn": "Reason for reaching out",
        "titleFr": "Reason for reaching out",
        "questionId": "",
        "validation": { "required": true },
        "subElements": [],
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      }
    },
    {
      "id": 13,
      "type": "textField",
      "uuid": "33635e8e-46d4-4720-905e-2c7de7c41044",
      "properties": {
        "choices": [{ "en": "", "fr": "" }],
        "titleEn": "Other ",
        "titleFr": "Autre ",
        "subElements": [],
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": "",
        "conditionalRules": [{ "choiceId": "12.4" }]
      }
    },
    {
      "id": 2,
      "type": "textField",
      "uuid": "611de7ef-d94d-48f3-bbad-e4219e2e6aef",
      "properties": {
        "tags": [],
        "choices": [{ "en": "", "fr": "" }],
        "titleEn": "Your name",
        "titleFr": "Your name",
        "questionId": "",
        "validation": { "required": true },
        "subElements": [],
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": "",
        "conditionalRules": []
      }
    },
    {
      "id": 8,
      "type": "richText",
      "uuid": "44736abd-6463-441b-810c-eec63697e4cf",
      "properties": {
        "choices": [{ "en": "", "fr": "" }],
        "titleEn": "",
        "titleFr": "",
        "validation": { "required": false },
        "subElements": [],
        "descriptionEn": "## How can we contact you?",
        "descriptionFr": "## Comment pouvons-nous vous contacter?",
        "placeholderEn": "",
        "placeholderFr": "",
        "conditionalRules": []
      }
    },
    {
      "id": 9,
      "type": "textField",
      "uuid": "8efda9f9-c64a-4673-bfb4-a3a5bfc0ef36",
      "properties": {
        "choices": [{ "en": "", "fr": "" }],
        "titleEn": "Phone number",
        "titleFr": "Numéro de téléphone",
        "validation": { "required": false },
        "subElements": [],
        "autoComplete": "tel",
        "descriptionEn": "For example: 111-222-3333",
        "descriptionFr": "Par exemple : 111-222-3333",
        "placeholderEn": "",
        "placeholderFr": "",
        "conditionalRules": []
      }
    },
    {
      "id": 10,
      "type": "textField",
      "uuid": "09cd2b30-3a3f-4fb5-8b56-d6396253fb70",
      "properties": {
        "choices": [{ "en": "", "fr": "" }],
        "titleEn": "Email address",
        "titleFr": "Adresse courriel",
        "validation": { "type": "email", "required": false },
        "subElements": [],
        "autoComplete": "email",
        "descriptionEn": "For example: name@example.com",
        "descriptionFr": "Par exemple : nom@exemple.com",
        "placeholderEn": "",
        "placeholderFr": "",
        "conditionalRules": []
      }
    },
    {
      "id": 11,
      "type": "radio",
      "uuid": "8531a7b5-47ec-47d9-a374-8d2a695a480e",
      "properties": {
        "choices": [
          { "en": "English", "fr": "anglais" },
          { "en": "French", "fr": "français" }
        ],
        "titleEn": "Preferred language for communication",
        "titleFr": "Langue de communication préférée",
        "validation": { "required": true },
        "subElements": [],
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": "",
        "conditionalRules": []
      }
    }
  ],
  "groups": {},
  "groupsLayout": ["b0e74a96-fa9e-43f4-8573-4b4ba23d65e5", "f926a616-80e2-4b93-a950-5e508f444c19"],
  "lastGeneratedElementId": 14
}

=== cds-snc/platform-forms-client/app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses-pilot/lib/__tests__/fixtures/template-equipment-list-2025-11-26.json
{
  "groups": {
    "end": {
      "name": "End",
      "titleEn": "Confirmation page",
      "titleFr": "Page de confirmation",
      "elements": []
    },
    "start": {
      "name": "Start",
      "titleEn": "Start page",
      "titleFr": "Page de départ",
      "elements": ["1"],
      "nextAction": "review"
    },
    "review": {
      "name": "Review",
      "titleEn": "End (Review page and Confirmation)",
      "titleFr": "Fin (Page récapitulative et confirmation)",
      "elements": [],
      "nextAction": "end"
    }
  },
  "layout": [1],
  "titleEn": "Equipment list",
  "titleFr": "",
  "elements": [
    {
      "id": 1,
      "type": "dynamicRow",
      "uuid": "df3e0a0f-aa04-47e5-aadb-d7e2b8d35ea0",
      "properties": {
        "tags": [],
        "choices": [
          {
            "en": "",
            "fr": ""
          }
        ],
        "titleEn": "List the names of the equipment you need",
        "titleFr": "",
        "dynamicRow": {
          "rowTitleEn": "Entry",
          "rowTitleFr": "Entrée",
          "addButtonTextEn": "Add",
          "addButtonTextFr": "Ajouter",
          "removeButtonTextEn": "Remove",
          "removeButtonTextFr": "Supprimer"
        },
        "questionId": "",
        "validation": {
          "required": false
        },
        "subElements": [
          {
            "id": 101,
            "type": "textField",
            "uuid": "7875b71d-5dc9-49d6-b3bc-71c52c37ef43",
            "properties": {
              "tags": [],
              "choices": [
                {
                  "en": "",
                  "fr": ""
                }
              ],
              "titleEn": "Name",
              "titleFr": "",
              "questionId": "",
              "validation": {
                "required": false
              },
              "subElements": [],
              "descriptionEn": "",
              "descriptionFr": "",
              "placeholderEn": "",
              "placeholderFr": ""
            }
          }
        ],
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": "",
        "maxNumberOfRows": 50
      }
    }
  ],
  "confirmation": {
    "descriptionEn": "",
    "descriptionFr": "",
    "referrerUrlEn": "",
    "referrerUrlFr": ""
  },
  "groupsLayout": [],
  "introduction": {
    "descriptionEn": "",
    "descriptionFr": ""
  },
  "privacyPolicy": {
    "descriptionEn": "",
    "descriptionFr": ""
  },
  "lastGeneratedElementId": 1
}
