=== cds-snc/platform-forms-client/lib/middleware/schemas/templates.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "id": "https://forms-formulaires.alpha.canada.ca/",
  "type": "object",
  "title": "GC Forms Schema - Alpha",
  "description": "A schema to define a Forms configuration.",
  "default": {},
  "examples": [
    {
      "titleEn": "",
      "titleFr": "",
      "introduction": {},
      "privacyPolicy": {},
      "confirmation": {},
      "layout": [],
      "elements": [],
      "startPage": {},
      "brand": {}
    }
  ],
  "properties": {
    "titleEn": {
      "description": "The displayed title of the form to the user in English",
      "id": "#/properties/titleEn",
      "type": "string"
    },
    "titleFr": {
      "description": "The displayed title of the form to the user in French",
      "id": "#/properties/titleFr",
      "type": "string"
    },
    "introduction": {
      "description": "Form introduction",
      "id": "#/properties/introduction",
      "type": "object",
      "properties": {
        "descriptionEn": {
          "type": "string"
        },
        "descriptionFr": {
          "type": "string"
        }
      }
    },
    "privacyPolicy": {
      "description": "Form privacy policy",
      "id": "#/properties/privacyPolicy",
      "type": "object",
      "properties": {
        "descriptionEn": {
          "type": "string"
        },
        "descriptionFr": {
          "type": "string"
        }
      }
    },
    "confirmation": {
      "description": "Content that will be displayed after a form is submitted.",
      "id": "#/properties/confirmation",
      "type": "object",
      "properties": {
        "descriptionEn": {
          "type": "string"
        },
        "descriptionFr": {
          "type": "string"
        },
        "referrerUrlEn": {
          "type": "string"
        },
        "referrerUrlFr": {
          "type": "string"
        }
      }
    },
    "layout": {
      "description": "A list of element IDs that determines the order or elements in the form.",
      "type": "array",
      "items": {
        "type": "number"
      },
      "uniqueItems": true,
      "examples": [[2, 3, 4, 6, 9, 5]]
    },
    "groups": {
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the group.",
          "type": "string"
        },
        "titleEn": {
          "description": "The title of the group in English.",
          "type": "string"
        },
        "titleFr": {
          "description": "The title of the group in French.",
          "type": "string"
        },
        "nextAction": {
          "description": "The next action to take i.e. next group or submit.",
          "type": "string"
        },
        "elements": {
          "description": "A list of elements contained within the form group.",
          "type": "array"
        }
      }
    },
    "groupsLayout": {
      "description": "A list of group IDs that determines the order of the groups in the form.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "examples": [["one", "two"]]
    },
    "elements": {
      "description": "A list of elements contained within the form.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/element"
      },
      "examples": [
        {
          "id": 1,
          "type": "richText",
          "properties": {
            "validation": {
              "required": false
            },
            "descriptionEn": "#### Section 1: Nomination Category",
            "descriptionFr": "#### Section 1: Catégorie de la nomination"
          }
        },
        {
          "id": 2,
          "uuid": "12345678-1234-1234-1234-123456789012",
          "type": "radio",
          "properties": {
            "questionId": "my_custom_id",
            "tags": ["radio", "nomination"],
            "choices": [
              {
                "en": "Team nomination",
                "fr": "Mise en candidature d’une équipe"
              },
              {
                "en": "Individual Nomination",
                "fr": "Mise en candidature d’une personne"
              }
            ],
            "titleEn": "Is this a Team or Individual Nomination?",
            "titleFr": "Is this a Team or Individual Nomination?",
            "validation": {
              "required": true
            },
            "descriptionEn": "",
            "descriptionFr": ""
          }
        }
      ]
    },
    "brand": {
      "type": "object",
      "properties": {
        "name": {
          "description": "The brand name.",
          "type": "string"
        },
        "urlEn": {
          "description": "URL for English version of the site.",
          "type": "string"
        },
        "urlFr": {
          "description": "URL for a French version of the site.",
          "type": "string"
        },
        "logoEn": {
          "description": "English logo path.",
          "type": "string"
        },
        "logoFr": {
          "description": "French logo path.",
          "type": "string"
        },
        "logoTitleEn": {
          "description": "logo title.",
          "type": "string"
        },
        "logoTitleFr": {
          "description": "logo title.",
          "type": "string"
        },
        "disableGCBranding": {
          "description": "If set to true, GC branding will not be rendered in the footer.",
          "type": "boolean"
        }
      }
    },
    "lastGeneratedElementId": {
      "description": "The last generated element id",
      "type": "number"
    }
  },
  "required": ["titleEn", "titleFr", "privacyPolicy", "confirmation", "layout", "elements"],
  "additionalProperties": false,
  "definitions": {
    "element": {
      "type": "object",
      "properties": {
        "id": {
          "description": "The unique id for the object",
          "type": "integer",
          "minimum": 1
        },
        "uuid": {
          "description": "A unique id for the object (future use)",
          "type": "string",
          "format": "uuid"
        },
        "type": {
          "type": "string",
          "enum": [
            "textField",
            "textArea",
            "dropdown",
            "radio",
            "checkbox",
            "fileInput",
            "dynamicRow",
            "richText",
            "attestation",
            "combobox",
            "addressComplete",
            "formattedDate"
          ]
        },
        "properties": {
          "type": "object",
          "properties": {
            "questionId": {
              "description": "A user-defined unique id for the question",
              "type": "string"
            },
            "tags": {
              "description": "A list of tags that can be used to group elements together.",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "titleEn": {
              "description": "Input label in English",
              "type": "string"
            },
            "titleFr": {
              "description": "Input label in French",
              "type": "string"
            },
            "placeholderEn": {
              "description": "Text that will appear in the text input field as a placeholder in English",
              "type": "string"
            },
            "placeholderFr": {
              "description": "Text that will appear in the text input field as a placeholder in French",
              "type": "string"
            },
            "descriptionEn": {
              "description": "Secondary paragraph/text of a question or element that provides additional context beyond the label in English",
              "type": "string"
            },
            "descriptionFr": {
              "description": "Secondary paragraph/text of a question or element that provides additional context beyond the label in French",
              "type": "string"
            },
            "dynamicRow": {
              "type": "object",
              "properties": {
                "rowTitleEn": {
                  "type": "string",
                  "description": "The title of the row in English"
                },
                "rowTitleFr": {
                  "type": "string",
                  "description": "The title of the row in French"
                },
                "addButtonTextEn": {
                  "type": "string",
                  "description": "Text for the add button in English"
                },
                "removeButtonTextEn": {
                  "type": "string",
                  "description": "Text for the remove button in English"
                },
                "addButtonTextFr": {
                  "type": "string",
                  "description": "Text for the add button in French"
                },
                "removeButtonTextFr": {
                  "type": "string",
                  "description": "Text for the remove button in French"
                }
              }
            },
            "choices": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "en": {
                    "description": "English choice",
                    "type": "string"
                  },
                  "fr": {
                    "description": "French choice",
                    "type": "string"
                  }
                }
              }
            },
            "sortOrder": {
              "type": "string",
              "description": "Controls how choices are displayed",
              "enum": ["none", "ascending", "descending"],
              "default": "none"
            },
            "managedChoices": {
              "type": ["array", "string"],
              "description": "The name of the data file(s) containing the choices for this element."
            },
            "conditionalRules": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "choiceId": {
                    "description": "The id of the element that will trigger the conditional rule",
                    "type": "string",
                    "minimum": 1
                  }
                }
              }
            },
            "maxNumberOfRows": {
              "type": "integer",
              "minimum": 1
            },
            "strictValue": {
              "description": "If set to true, the element will only accept values that are in the choices list.",
              "type": "boolean"
            },
            "validation": {
              "type": "object",
              "properties": {
                "required": {
                  "type": "boolean"
                },
                "type": {
                  "type": "string",
                  "enum": ["email", "alphanumeric", "text", "name", "number", "phone", "date"]
                },
                "regex": {
                  "type": "string"
                },
                "maxLength": {
                  "description": "The maximum number of characters that can be entered in a textinput or textarea.",
                  "type": "integer",
                  "minimum": 1
                },
                "descriptionEn": {
                  "type": "string"
                },
                "descriptionFr": {
                  "type": "string"
                },
                "all": {
                  "description": "Used only for checkboxes, ignored on other elements. When set to true, this will require that all checkboxes be selected. Used typically for the attestation section.",
                  "type": "boolean"
                }
              },
              "examples": [
                {
                  "validation": {
                    "required": true,
                    "type": "email",
                    "descriptionEn": "Enter a valid email address.",
                    "descriptionFr": "Veuillez entrer une adresse courriel valide."
                  }
                },
                {
                  "validation": {
                    "required": false,
                    "type": "alphanumeric",
                    "descriptionEn": "Please enter your home street address.",
                    "descriptionFr": "Veuillez entrer votre adresse postale."
                  }
                }
              ]
            },
            "subElements": {
              "description": "A list of subElements contained within a dynamicRow",
              "type": "array",
              "items": {
                "$ref": "#/definitions/element"
              }
            }
          }
        }
      },
      "required": ["id", "type", "properties"]
    }
  }
}

=== cds-snc/platform-forms-client/components/form-builder/example-form.json
{
  "titleEn": "Lemonade Stand Funding",
  "titleFr": "[fr] Lemonade Stand Funding",
  "introduction": {
    "descriptionEn": "Introduction",
    "descriptionFr": "[FR] Introduction"
  },
  "privacyPolicy": {
    "descriptionEn": "Privacy statement",
    "descriptionFr": "Déclaration de confidentialité"
  },
  "confirmation": {
    "descriptionEn": "#Your submission has been received \n\r Thank you for your interest. We will contact you within 3-5 business days.  \n\r <a href='https://digital.canada.ca'>Go back</a>",
    "descriptionFr": "#[fr] Your submission has been received. \n\r Thank you for your interest. We will contact you within 3-5 business days. \n\r <a href='https://digital.canada.ca'>Go back</a>",
    "referrerUrlEn": "",
    "referrerUrlFr": ""
  },
  "layout": [1, 2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14],
  "elements": [
    {
      "id": 1,
      "type": "richText",
      "properties": {
        "charLimit": 5000,
        "validation": {
          "required": false
        },
        "descriptionEn": "##Contact Information",
        "descriptionFr": "##[fr] Contact Information"
      }
    },
    {
      "id": 2,
      "type": "textField",
      "properties": {
        "titleEn": "1. What is your name?",
        "titleFr": "[fr]1. What is your name?]",
        "validation": {
          "type": "text",
          "required": true,
          "maxLength": 150
        },
        "autoComplete": "name",
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      }
    },
    {
      "id": 3,
      "type": "radio",
      "properties": {
        "choices": [
          {
            "en": "English",
            "fr": "Anglais"
          },
          {
            "en": "French",
            "fr": "Français"
          }
        ],
        "titleEn": "2. What is your preferred language for communications?",
        "titleFr": "[fr] 2. What is your preferred language for communications?",
        "validation": {
          "required": true
        },
        "descriptionEn": "",
        "descriptionFr": ""
      }
    },
    {
      "id": 4,
      "type": "richText",
      "properties": {
        "charLimit": 5000,
        "validation": {
          "required": false
        },
        "descriptionEn": "**Note:** We are not collecting email addresses or phone numbers through this test form to preserve your privacy \n\r ##Poject Information",
        "descriptionFr": "[fr] **Note:** We are not collecting email addresses or phone numbers through this test form to preserve your privacy \n\r ##Project Information"
      }
    },
    {
      "id": 5,
      "type": "textField",
      "properties": {
        "titleEn": "3. What is the name of your lemonade stand?",
        "titleFr": "[fr]3. What is the name of your lemonade stand?",
        "validation": {
          "type": "text",
          "required": true,
          "maxLength": 300
        },
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      }
    },
    {
      "id": 7,
      "type": "textArea",
      "properties": {
        "titleEn": "5. Please describe the taste of your lemonade recipe. ",
        "titleFr": "[fr] 5. Please describe the taste of your lemonade recipe. ",
        "validation": {
          "type": "text",
          "required": true,
          "maxLength": 1000
        },
        "descriptionEn": "Consider including details about the sweetness or sourness of your lemonade recipe. Maximum characters: 1000",
        "descriptionFr": "[fr]Consider including details about the sweetness or sourness of your lemonade recipe. Maximum characters: 1000",
        "placeholderEn": "",
        "placeholderFr": ""
      }
    },
    {
      "id": 8,
      "type": "dropdown",
      "properties": {
        "choices": [
          {
            "en": "Park",
            "fr": "[fr] Park"
          },
          {
            "en": "Driveway",
            "fr": "[fr]Driveway"
          },
          {
            "en": "Building lobby",
            "fr": "[fr]Building lobby"
          },
          {
            "en": "Parking lot",
            "fr": "[fr]Parking lot"
          },
          {
            "en": "Other",
            "fr": "[fr]Other"
          }
        ],
        "titleEn": "6. Where is your lemonade stand going to be located?",
        "titleFr": "[fr]6. Where is your lemonade stand going to be located?",
        "validation": {
          "required": true
        },
        "descriptionEn": "",
        "descriptionFr": ""
      }
    },
    {
      "id": 9,
      "type": "textField",
      "properties": {
        "titleEn": "7. If you checked Other, please specify",
        "titleFr": "7. Pour d'autre information veuillez spécifier",
        "validation": {
          "type": "text",
          "required": false,
          "maxLength": 100
        },
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      }
    },
    {
      "id": 10,
      "type": "richText",
      "properties": {
        "charLimit": 5000,
        "validation": {
          "required": false
        },
        "descriptionEn": "###Materials and Ingredients",
        "descriptionFr": "###[fr] Materials and Ingredients"
      }
    },
    {
      "id": 12,
      "type": "checkbox",
      "properties": {
        "choices": [
          {
            "en": "Cups",
            "fr": "[fr] Cups"
          },
          {
            "en": "Napkins",
            "fr": "[fr]Napkins"
          },
          {
            "en": "Straws",
            "fr": "[fr]Straws"
          }
        ],
        "titleEn": "9. Which materials will you purchase with this funding? ",
        "titleFr": "[fr] 9. Which materials will you purchase with this funding? ",
        "validation": {
          "required": true
        },
        "descriptionEn": "",
        "descriptionFr": ""
      }
    },
    {
      "id": 13,
      "type": "richText",
      "properties": {
        "charLimit": 5000,
        "validation": {
          "required": false
        },
        "descriptionEn": "##Submission",
        "descriptionFr": "##[fr] Submission"
      }
    },
    {
      "id": 14,
      "type": "radio",
      "properties": {
        "choices": [
          {
            "en": "Yes",
            "fr": "Oui"
          },
          {
            "en": "No",
            "fr": "Non"
          }
        ],
        "titleEn": "10. Do you attest that the information you are providing is true and correct to your knowledge?",
        "titleFr": "[fr] 10. Do you attest that the information you are providing is true and correct to your knowledge?",
        "validation": {
          "required": true
        },
        "descriptionEn": "",
        "descriptionFr": ""
      }
    }
  ]
}

=== cds-snc/platform-forms-client/__fixtures__/testData.json
{
  "titleEn": "Test Form",
  "titleFr": "Formulaire de test",
  "confirmation": {
    "descriptionEn": "",
    "descriptionFr": "",
    "referrerUrlEn": "https://digital.canada.ca/",
    "referrerUrlFr": "https://numerique.canada.ca/"
  },
  "layout": [1, 2, 3, 4, 5, 6, 7, 8],
  "privacyPolicy": {
    "descriptionEn": "Privacy statement",
    "descriptionFr": "[FR] Privacy statement"
  },
  "elements": [
    {
      "id": 1,
      "type": "textField",
      "properties": {
        "titleEn": "What is your full name?",
        "titleFr": "Quel est votre nom complet?",
        "placeholderEn": "I wish I knew",
        "placeholderFr": "Je ne sais pas",
        "descriptionEn": "This is a description",
        "descriptionFr": "Voice une description",
        "validation": {
          "required": true
        }
      }
    },
    {
      "id": 2,
      "type": "textArea",
      "properties": {
        "titleEn": "What is the problem you are facing",
        "titleFr": "Quel est le problème auquel vous êtes confronté?",
        "placeholderEn": "Something difficult",
        "placeholderFr": "Quelque chose difficile",
        "descriptionEn": "Here be a description",
        "descriptionFr": "Pour décrire, ou pas décire..",
        "validation": {
          "required": true
        }
      }
    },
    {
      "id": 3,
      "type": "richText",
      "properties": {
        "titleEn": "",
        "titleFr": "",
        "descriptionEn": "Thank you so much for your interest in the Canadian Digital Service’s Forms product. \n\r\n\r Please provide your information below so CDS can contact you about improving, updating, or digitizing a form.",
        "descriptionFr": "Merci beaucoup de l’intérêt que vous portez au produit de Formulaire du Service Numérique Canadien. \n\r\n\r Veuillez fournir vos renseignements ci-dessous afin que le SNC puisse vous contacter pour discuter davantage l'amélioration, la mise à jour ou la numérisation d'un formulaire.",
        "validation": {
          "required": false
        }
      }
    },
    {
      "id": 4,
      "type": "dropdown",
      "properties": {
        "titleEn": "Province or territory",
        "titleFr": "Province ou territoire",
        "placeholderEn": "",
        "placeholderFr": "",
        "descriptionEn": "",
        "descriptionFr": "",
        "choices": [
          {
            "en": "",
            "fr": ""
          },
          {
            "en": "Alberta",
            "fr": "Alberta"
          },
          {
            "en": "British Columbia",
            "fr": "Colombie-Britannique"
          },
          {
            "en": "Manitoba",
            "fr": "Manitoba"
          },
          {
            "en": "New Brunswick",
            "fr": "Nouveau-Brunswick"
          },
          {
            "en": "Newfoundland and Labrador",
            "fr": "Terre-Neuve-et-Labrador"
          },
          {
            "en": "Northwest Territories",
            "fr": "Territoires du Nord-Ouest"
          },
          {
            "en": "Nova Scotia",
            "fr": "Nouvelle-Écosse"
          },
          {
            "en": "Nunavut",
            "fr": "Nunavut"
          },
          {
            "en": "Ontario",
            "fr": "Ontario"
          },
          {
            "en": "Prince Edward Island",
            "fr": "Île-du-Prince-Édouard"
          },
          {
            "en": "Quebec",
            "fr": "Québec"
          },
          {
            "en": "Saskatchewan",
            "fr": "Saskatchewan"
          },
          {
            "en": "Yukon",
            "fr": "Yukon"
          }
        ],
        "validation": {
          "required": false
        }
      }
    },
    {
      "id": 5,
      "type": "radio",
      "properties": {
        "titleEn": "Status",
        "titleFr": "Statut",
        "description": "",
        "validation": {
          "required": false
        },
        "choices": [
          {
            "en": "Citizen",
            "fr": "Cityoen"
          },
          {
            "en": "Permanent Resident",
            "fr": "Permanent Resident"
          },
          {
            "en": "Student",
            "fr": "Student"
          },
          {
            "en": "Visitor",
            "fr": "Visitor"
          },
          {
            "en": "Other",
            "fr": "Autre"
          }
        ]
      }
    },
    {
      "id": 6,
      "type": "checkbox",
      "properties": {
        "titleEn": "Will the project or any of its activities involve or benefit people in English or French linguistic minority communities in Canada, in some way?",
        "titleFr": " Le projet ou les activités connexes impliquent-ils ou s’adressent-ils d’une façon ou d’une autre aux minorités francophones et anglophones du Canada?",
        "validation": {
          "required": false
        },
        "choices": [
          {
            "en": "Yes",
            "fr": "Oui"
          },
          {
            "en": "No",
            "fr": "Non"
          },
          {
            "en": "Not Applicable",
            "fr": "Non applicable"
          }
        ]
      }
    },
    {
      "id": 7,
      "type": "dynamicRow",
      "properties": {
        "titleEn": "",
        "titleFr": "",
        "validation": {
          "required": false
        },
        "subElements": [
          {
            "id": 22,
            "type": "textField",
            "properties": {
              "titleEn": "Family name",
              "titleFr": "Nom",
              "placeholderEn": "",
              "placeholderFr": "",
              "descriptionEn": "",
              "descriptionFr": "",

              "validation": {
                "required": false
              }
            }
          },
          {
            "id": 22,
            "type": "textField",
            "properties": {
              "titleEn": "Given name",
              "titleFr": "Prénom",
              "laceholderEn": "",
              "placeholderFr": "",
              "descriptionEn": "",
              "descriptionFr": "",
              "validation": {
                "required": false
              }
            }
          },
          {
            "id": 22,
            "type": "textField",
            "properties": {
              "titleEn": "Department or organization",
              "titleFr": "Ministère ou organisme",
              "placeholderEn": "",
              "placeholderFr": "",
              "descriptionEn": "",
              "descriptionFr": "",
              "validation": {
                "required": false
              }
            }
          },
          {
            "id": 22,
            "type": "checkbox",
            "properties": {
              "titleEn": "Will the project or any of its activities involve or benefit people in English or French linguistic minority communities in Canada, in some way?",
              "titleFr": " Le projet ou les activités connexes impliquent-ils ou s’adressent-ils d’une façon ou d’une autre aux minorités francophones et anglophones du Canada?",
              "validation": {
                "required": false
              },
              "choices": [
                {
                  "en": "Yes",
                  "fr": "Oui"
                },
                {
                  "en": "No",
                  "fr": "Non"
                },
                {
                  "en": "Not Applicable",
                  "fr": "Non applicable"
                }
              ]
            }
          }
        ]
      }
    },
    {
      "id": 8,
      "type": "textField",
      "properties": {
        "titleEn": "This Answer is empty?",
        "titleFr": "Ce reponse est vide?",
        "placeholderEn": "yuppers",
        "placeholderFr": "oui",
        "descriptionEn": "This is a description",
        "descriptionFr": "Voice une description",
        "validation": {
          "required": false
        }
      }
    }
  ],
  "brand": {
    "name": "cds-snc",
    "logoEn": "https://digital.canada.ca/img/cds/cds-lockup-ko-en.svg",
    "logoFr": "https://numerique.canada.ca/img/cds/cds-lockup-ko-fr.svg",
    "logoTitleEn": "Canadian Digital Service",
    "logoTitleFr": "Service numérique canadien",
    "urlEn": "https://digital.canada.ca/",
    "urlFr": "https://numerique.canada.ca/"
  }
}
